### ISSUE TITLE
Colorblindness issue

### ISSUE THREAD

**Issue by snotbane** [renpy/language-renpy#14]
Hey guys, I really like renpy and I've been having a blast getting to know the software, but I'm having issues with the color scheming in Atom. I'm slightly colorblind, and it makes it difficult to read certain words, especially in your custom-made theme for Atom. Would it be possible to make your theme more easily editable for an old coot like me?

**Comment by renpytom** [comment]
Writing a custom theme is difficult, but it's pretty easy to chang it. Go into the settings (Either File/Settings, Edit/Preferences, or Atom/Preferences), then click on Theme. There are a bunch it comes with, and you ca get more by going to the plugins tab and installing new themes.
