### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by renpytom** [renpy/language-renpy#2]
It would be nice if the README covered how to get started with Ren'Py and Atom, at least for those of us who aren't familiar with the latter.

**Comment by williamd1k0** [comment]
Oh, of course! I'll edit to put well explained how to use and everything. I'll just take a while because I do not speak English and I will ask for a friend to translate, because google translator does not help 100%.

**Comment by williamd1k0** [comment]
So, I'll leave the Getting Started for the end because I will still create snippets.
An example of snippets in the gif below:

![Snippets](http://i.gyazo.com/e8adaed0ea77d69bc5fed058fb60951d.gif)

**Comment by williamd1k0** [comment]
Hi, I published the package with a very basic documentation on README, talking about the basic usage and snippets.

I took a lot for personal problems and unfortunately will not be able to dedicate myself to improve the package directly, only attending to suggestions and pull requests.

Thank you for your support always improving Ren'Py!
